version: "3.9"

services:
  bot:
    build: .
    container_name: vpn-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/wireguard:/etc/wireguard
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    privileged: true
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: wg-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wg_user
      POSTGRES_PASSWORD: TQeKg4qHQ2CWOjKnlVXMwe/H5bBK811BfjcpEx1o
      POSTGRES_DB: wg_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: